services:
  poke-app:
    build: .
    container_name: poke-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
    restart: unless-stopped